### ISSUE TITLE
Simplify Reading Files

### ISSUE THREAD

**Issue by smangham** [CorentinLouis/SPACE_labelling_tool#1]
We'd like to simplify reading the files, by peeking at them to identify things like columns and start dates, then re-reading them fully. The code currently uses `scipy.io` to read the file, which can only read the *whole* file - are there any ways around this?

`pyreadstat` & `pandas.read_spss` don't work, giving the error "Invalid file or unsupported features".

**Comment by CorentinLouis** [comment]
Unfortunately, to read a ".sav" file, the only way is to use scipy.io.readsav package.

**Comment by smangham** [comment]
Right, pushed an update to my feature branch. This adds a `setup.py` file so the code can be pip installed, and simplifies starting the code to e.g.
```
space_label.py SKR_2004_CJ.sav 2004123 2004143
```
* Satellite is auto-detected from the columns in the input file, compared to a set of configuration files.
  * If multiple files match, the user can specify the configuration with a `-c` argument e.g. `-c cassini`. 
* Year-of-origin is auto-detected from the first number in the input filename e.g. `SKR_2004_11_123.sav` would auto-detect 2004.
  * This is validated against the data in the file and the satellite operational years, e.g. if the data goes from DOY 1-730,
    then it would throw an error if the satellite was not operational across the entire range 2004 - 2005.
  * A year-of-origin can be specified manually using the `-y` argument e.g. `-y 1997`.
* Date ranges are similarly validated against the contents of the data file and the operational period of the satellite.

There's pretty aggressive validation and descriptive error messages, so it should be clear if someone makes a mistake (e.g. not providing the year-of-origin if the first number in the filename is invalid).

This currently *just* wraps the original python file, with a few small modifications (to remove its dependency on a global variable). Next step is meddling with it.

**Comment by smangham** [comment]
Addressed in #5
