### ISSUE TITLE
Working only on the matplotlib window

### ISSUE THREAD

**Issue by CorentinLouis** [CorentinLouis/SPACE_labelling_tool#2]
We would like to be able to work only in the graphical window "matplotlib" rather than going back and forth between this window and the terminal.

Example: when the user is asked to enter a feature name for the polygon he has just drawn, this should be done in the graphical window and not in the terminal (moreover, it should be asked AFTER the user has drawn his polygon, and not before the user has drawn it).

(For this, see what Shane Maloney has written)

**Comment by smangham** [comment]
Done in dev
