### ISSUE TITLE
Plot intensity and polarisation data (where available) and be able to draw polygons in either of the dynamic spectra. 

### ISSUE THREAD

**Issue by CorentinLouis** [CorentinLouis/SPACE_labelling_tool#3]
We would like to be able to plot both the dynamic spectra containing intensity and polarisation (whenever available) information, one above the other in the graphics window.

We would then like to be able to draw polygons in either of the dynamic spectra. Once this is done, the program should be able to draw the selected polygon in the other window (and of course save it into the json file).

**Comment by smangham** [comment]
This is done on the dev branch.
